### ISSUE TITLE
Update Invoke-RelativityInstall function to stop/start appropriate Relativity services prior to and after installs

### ISSUE THREAD

**Issue by Kimmels-n-Bits** [Kimmels-n-Bits/PSRelativityConfig#13]
After starting the Relativity Secret Store service we'll want to run another function to unseal the secret store

**Comment by Oasis-MS** [comment]
Service start/stop have been implemented.
However, Invoke-RelativityInstall will be rewritten using the newer framework.

Invoke-RelativityInstall handled on separate issue.
unsealing RSS will be handled on a separate issue.
