### ISSUE TITLE
Add ability to save RelativityInstance object as a serialized JSON file

### ISSUE THREAD

**Issue by Oasis-JK** [Kimmels-n-Bits/PSRelativityConfig#7]
Might have some concerns about linked credentials? Maybe don't include in JSON and request credentials again when loading the JSON

**Comment by Oasis-MS** [comment]
this can be a long running task.  so json will provide option for running beforehand

**Comment by Oasis-MS** [comment]
this is implemented using the newer object model [Instance]

ex. 
$json = $myInstance.ToJson()
$myInstance2.FromJson($json)
$myInstance2.FromJsonFile($path)
